name: PR Audit

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  textformat:
    runs-on: ubuntu-latest
    env:
      ALWAYS_LINT_ALL_FILES: false
      EC_FIX_ERROR: false

    steps:
      - uses: actions/checkout@v2
      - name: EditorConfig-Action
        uses: zbeekman/EditorConfig-Action@master
