name: CI

on:
  push:
    branches:
      - '**'
      - '*'
  pull_request:
    branches:
      - '**'
      - '*'
  workflow_dispatch:

jobs:
  textformat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: EditorConfig-Action
        uses: zbeekman/EditorConfig-Action@master
