name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  textformat:
    runs-on: ubuntu-latest
    env:
      ALWAYS_LINT_ALL_FILES: true

    steps:
      - name: EditorConfig-Action
        uses: zbeekman/EditorConfig-Action@master
