name: PR Audit
on: pull_request

jobs:
  textformat:
    name: EditorConfig audit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: EditorConfig-Action
        uses: zbeekman/EditorConfig-Action@master
        env:
          ALWAYS_LINT_ALL_FILES: false
          EC_FIX_ERROR: false
